### ISSUE TITLE
Edi Failing every time opening AvalonDock.

### ISSUE THREAD

**Issue by rasyidf** [Dirkster99/Edi#3]
Edi keep failing when opening Avalon dock tab on right or bottom window. 

`System.ComponentModel.Win32Exception occurred
  HResult=0x80004005
  Message=The operation completed successfully
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at MS.Win32.UnsafeNativeMethods.CreateWindowEx(Int32 dwExStyle, String lpszClassName, String lpszWindowName, Int32 style, Int32 x, Int32 y, Int32 width, Int32 height, HandleRef hWndParent, HandleRef hMenu, HandleRef hInst, Object pvParam)
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
   at System.Windows.Window.EnsureHiddenWindow()
   at System.Windows.Window.SetTaskbarStatus()
   at System.Windows.Window.CreateAllStyle()
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()`

**Comment by Dirkster99** [comment]
Is this still happing if you previously remove the setting and session files at:
C:\Users\<Windows UserName>\AppData\Roaming\Edi\
?

**No**> If no, its probably an incompateability to a previous version of Avalondock.

**Yes**> if yes, I am not sure how to verify this problem as it seems to work for me. Can you provide a series of screencaptures of a video to understand better how the problem can be caused to occur?

**Comment by rasyidf** [comment]
Ok, I'll marked as won't fix because it's component issue and we can't do anything else. closed.

**Comment by yogithesymbian** [comment]
> Ok, I'll marked as won't fix because it's component issue and we can't do anything else. closed.

whats mean of component issue ? can you explain what is it ? i have same issue with opening .exe file ( mod game nfs )

**Comment by rasyidf** [comment]
Sorry for closing without explaination, here i am 7 years from the future, 😅

This error is due to a failure in a COM component, likely related to window creation (CreateWindowEx). The generic HResult=0x80004005 indicates an unspecified failure. Common causes include missing dependencies, incompatibilities, or insufficient permissions.

---

Little Notes; This issue is categorized as a "component issue" because it stems from a problem within the underlying system or external library (a component) that the application relies on.
